
### compare the prediction of our map and other maps

##y_s.txt consists of three column: DTB of our study, DTB of Pelletier et al(2016). and Shangguan et al(2017)
##y_s.txt is generated by GIS
depthDF<-read.table("F:/China/d/y_s.txt",header = TRUE,sep = ",")
depthDF$depth<-depthDF$depth/100
depthDF$BDTICM_M_2<-depthDF$BDTICM_M_2/100
depthDF$sed_dep<-depthDF$sed_dep/100

cor(depthDF$depth,depthDF$BDTICM_M_2)
sqrt(mean((depthDF$depth - depthDF$BDTICM_M_2)^2, na.rm=TRUE))
mean(depthDF$depth-depthDF$BDTICM_M_2)

cor(depthDF$depth,depthDF$sed_dep)
sqrt(mean((depthDF$depth - depthDF$sed_dep)^2, na.rm=TRUE))
mean(depthDF$depth-depthDF$sed_dep)

cor(depthDF$BDTICM_M_2,depthDF$sed_dep)
sqrt(mean((rf.mp$meas - rf.mp$pred)^2, na.rm=TRUE))


band1<-read.table("F:/China/d/y_s.txt",header = TRUE,sep = ",")
band1$dis<-sqrt((band1$lon-108.93)**2+(band1$lat-34.27)**2)
band1<-band1[sort(band1$dis,decreasing = FALSE),]
plot(band1$dis,band1$depth,type="n")
lines(band1$dis,band1$BDTICM_M_2)
lines(band1$dis,band1$depth,col="red")
lines(band1$dis,band1$China_dem*10,col="blue")
nrow(band1)
